### PR TITLE
Update Spotlight for IIIF-Crop

### PR DESCRIPTION
**Pull request by tpendragon**
We'll have to reindex everything in production to get this to work, but it works really well.

### CODE REVIEW

**Comment by jpstroop** [comment]
Can we hold of on the push to production and reindex until Friday?

**Comment by tpendragon** [comment]
Nope! We can roll back if we want, but it's already done.

**Comment by jpstroop** [comment]
Oh, OK. I didn't see the deploy go by. Has the reindex happened as well?

**Comment by tpendragon** [comment]
I had it running yesterday but it got killed for taking up RAM. I ran a more efficient one an hour or so ago, and it's plugging along nicely.

**Pull request merged**
