### PR TITLE
Aligning the header and footer CSS style rules with those of Orangelight

### LINKED ISSUE #421: Headers/footers should match main Library website

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #421

### CODE REVIEW

**Comment by escowles** [comment]
This is a good start — I think the main other thing we should do is pull the "Digtal PUL" header into the black header bar the way that OL does with "Catalog".

**Comment by hackmastera** [comment]
The place where it says "Digital PUL" is used on collection pages to show the collection name.  So we'll need to make sure not to remove the area altogether; i guess just on index.

**Comment by escowles** [comment]
I think it's fine to leave the search box as-is to allow more space for browse page titles.

**Comment by sdellis** [comment]
I suggest using the LUX header/footer in to keep it in sync with other apps.

**Comment by escowles** [comment]
@sdellis I think we'll start using Lux as part of #440 — hopefully early in 2019.

**Pull request merged**
