### PR TITLE
Split HTML title with commas, not <br>

### LINKED ISSUE #280: Formatting appearing in window title
Tom V. reported some encoding appearing between romanized and script titles in the window name.

image

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #280

### CODE REVIEW

**Comment by hackmastera** [comment]
Why the decision to use commas instead of line breaks?

**Comment by hackmastera** [comment]
I know that figgy uses line breaks... idk what that means for pomegranate!

**Comment by hackmastera** [comment]
oh I guess that's for multiple title entries. Is this different?

**Comment by escowles** [comment]
This ticket is for the page title only, right?  The display title in the page should still be separated with `<br/>` to allow LTR and RTL text to display appropriately.

**Comment by hackmastera** [comment]
oh geez, i was confused. thanks for clarifying @escowles!

**Pull request merged**
