### PR TITLE
Upgrade Spotlight

### PR DESCRIPTION
**Pull request by tpendragon**
Steps for upgrade:

1. `bundle update blacklight-spotlight rails`
1. Install new migrations, follow directions in upgrade notes.
1. Copy over new versions of overridden views.
1. Get tests passing.
1. Fix weird route thing.

### CODE REVIEW

**Comment by escowles** [comment]
This looks good to me — looks ready to deploy to staging for some manual testing, once that's working.

**Comment by hackmastera** [comment]
Please rebase before deploying for further testing!

**Comment by tpendragon** [comment]
I tested this on staging and things wouldn't reindex. I just rebased so I could test again later, when Kim doesn't need it.

**Comment by tpendragon** [comment]
I tested this and things were indexing and displaying fine. Needs confirmation from @kelea99

**Pull request merged**
