### PR TITLE
fix footer content centering, stickiness

### LINKED ISSUE #539: Issue with CSS for DPUL footer
screen shot 2019-03-01 at 10 12 06 am 3

The footer doesn't appear to be fixed.

### PR DESCRIPTION
**Pull request by hackmastera**
resolves #539

### CODE REVIEW

**Comment by hackmastera** [comment]
tested on chrome, ff, safari. need to test IE. here's a screenshot:

screen shot 2019-03-01 at 4 07 24 pm

**Comment by hackmastera** [comment]
(bottom of footer is below the fold)

**Comment by hackmastera** [comment]
We checked it on IE and it looks good. If you want to see yourself it's deployed on staging.

**Comment by escowles** [comment]
Looks good to me on MacOSX (Firefox, Chrome and Safari)

**Pull request merged**
