### PR TITLE
Reduce exhibit-card image size and allow more cards per row on home page

### LINKED ISSUE #377: Remove blank right column from home
For cleaner look

screen shot 2018-06-20 at 3 58 55 pm

### PR DESCRIPTION
**Pull request by hackmastera**
fixes #377

### CODE REVIEW

**Comment by escowles** [comment]
Can you post screen shots showing the backs of some of the collections with longer descriptions (e.g. `scheide` and `islamicmss`?) — it's been a struggle to get those descriptions to fit.

**Comment by hackmastera** [comment]
@escowles good call; the islamicmss is running down too far. the container width is a bootstrap breakpoint so I was hesitant to adjust that. I could bump the thumbnail size back up and reduce margins? I will mess around.

screen shot 2018-06-22 at 8 54 07 am

**Comment by escowles** [comment]
This is beyond my CSS skills — but it occurs to me that the focused card could be bigger and overflow the side of the face-up cards — which could give us more room for the description while keeping the compact display.

**Comment by hackmastera** [comment]
At that point i might wonder why we wouldn't just use a modal. the whole mechanism is fishy to me, honestly; you can't click on the back of the card unless you can hover on it? seems like an accessibility issue. on mobile it looks like you can tap but i'm not sure whether there are sufficient cues for a screenreading user.

Some UX tickets on this repo would be welcome; ;I believe there are some upstream that would be relevant. e.g. this one tripped me up yesterday even though I clearly already knew about it from the code4lib workshop: https://github.com/projectblacklight/spotlight/issues/1897

**Comment by hackmastera** [comment]
here's a screenshot of the latest effort
screen shot 2018-06-22 at 10 15 09 am

**Comment by escowles** [comment]
@hackmastera I agree about the card-flip animation — that's always seemed annoying to me.

**Pull request merged**
