### PR TITLE
Turn bookmarks back on

### LINKED ISSUE #567: Add Bookmarks and CSV download functionalities to DPUL
This also came up during the 15M ephemera meeting I had with Fernando yesterday. can we have it mirror that of the catalog? Screenshot_bookmarks-downloads

### PR DESCRIPTION
**Pull request by hackmastera**
refs #567

### CODE REVIEW

**Comment by tpendragon** [comment]
This works, but bookmarks aren't saved in context of their exhibit. Is that a problem we want to look at? Maybe a follow-on ticket?

**Comment by escowles** [comment]
I'm not sure how important this is — maybe @kelea99 has an opinion on this?  Since the item pages link to the exhibits they are members of, maybe that's enough?

**Comment by kelea99** [comment]
I don’t believe it is that important to know what exhibit the items come from, since they are tagged with the collections they are a part of and it’s viewable in the metadata. At least that’s my two cents.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hackmastera** [comment]
It's more than just what exhibit it came from, though; the metadata customizations are per-exhibit. E.g. The 'curatorial note' would not show, or any other metadata choices that had been made. Probably also the title overrides. It could be sort of confusing to people.

And if they want to get back to the view of the item in the context of the collection, it's probably not clear how they would do that. They would have to go to the collection then search again for the item there.

I understand why things are different depending on the collection context, but I do worry that it's confusing for people.

Just wanted to make sure the concern was entirely clear. If y'all still think it's not important I am on board! If we do want to address it, I would vote for a follow-on ticket.

**Comment by kelea99** [comment]
@hackmastera I'm just seeing this now.  Thanks so much for the clarification/information. @tpendragon, is it too late to chime in again?

**Comment by escowles** [comment]
@kelea99 It's never too late — we went ahead and merged this, with the idea that we'd create a new issue to figure out which exhibit an item was from if someone asked for that. If you want to ask for it *now*, go ahead!

**Comment by kelea99** [comment]
@escowles thanks.  I think @hackmastera raises important points. I can envision customized metadata (primarily the curatorial notes) being added to more than just the DPUL exhibits that parallel the physical exhibits in the future.  So, if I may change my mind? Yup. Id like to ask for it now.  The metadata customizations per exhibit should hang out with the bookmarked item.  Sorry, y'all for my flip flop.

**Pull request merged**
