### PR TITLE
Update universal viewer and improve fullscreen exit

### LINKED ISSUE #97: UV doesn't take up full screen when going "full screen"
screenshot from 2016-05-26 13-40-34

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #97 

- Brings in the Princeton fork of universal viewer using bower. Same as plum does now.
- Adds the ability to transpile es6.
- Corrects issue with exiting fullscreen mode in the universal viewer.

### CODE REVIEW

**Comment by tpendragon** [comment]
Pomegranate uses an external UV, doesn't it? Wouldn't you just have to update `uv-dev.princeton.edu`?

**Comment by eliotjordan** [comment]
Why does it use an external uv?

**Comment by tpendragon** [comment]
Largely so we don't have to embed all of UV in Pomegranate.

**Comment by eliotjordan** [comment]
Although that's what happens in plum. Just seems a bit weird to have an entire domain name just to serve a javascript library to a single application. If the idea is to use that copy in multiple apps, then it's a little better I guess.

**Comment by tpendragon** [comment]
The goal is to use it in multiple applications - plum, too. We just can't now because we don't have IIIF auth figured out, so not crossing boundary domains is the only way we can get a hold of IIIF manifests which are private.

**Comment by eliotjordan** [comment]
I'm sure I'm missing some of the subtleties here, but  to me, UV doesn't seem much different than a library like JQuery, other than we need a customized version. How about wrapping it up as a gem to abstract away some of the messy bower/js business? Just add `'princeton-uv', '1.7.1'` to your Gemfile and off you go. Just a thought. Anyways, maybe we can chat about this at the sprint retro on Monday.

**Comment by eliotjordan** [comment]
I whipped up a small rails engine wrapper for the PUL-branded Universal Viewer and added it to pomegranate instead. I think this is a nice solution. A simple, versioned gem with an included script tag helper.

**Comment by eliotjordan** [comment]
Configured rails to serve static files. Seems to be working in production.

**Comment by eliotjordan** [comment]
Giving this PR an electronic dap. Can this be merged, or are other updates needed?

**Pull request merged**
