### PR TITLE
Added locale dropdown to user util links

### LINKED ISSUE #863: Language dropdown does not appear when a language has been made public
The UI doesn't show the language selector, probably due to our branding overrides.

Here's a screenshot from a stanford site:
Screen Shot 2020-12-09 at 5 02 09 PM

### PR DESCRIPTION
**Pull request by kelynch**
Closes #863

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
Thank you! 

Okay this works and it does close the ticket but I'm not sure we should merge it yet because the translations still don't show up once I select a language. We may have lost more than just the dropdown.

So I'm saying "Request changes" but just as a way to block merge, not because there should be anything else in this PR.

**Comment by hackartisan** [comment]
I've asked for more analysis and feedback from the PO

**Comment by kelea99** [comment]
Thank you @hackartisan and @kelynch ! made a ticket for the translations that do not show: https://github.com/pulibrary/pomegranate/issues/866

**Comment by hackartisan** [comment]
Okay @kelea99 's suggestion was to merge / deploy this and she will make the languages not public in the relevant exhibits until enough from #866 is done for it to make sense.

**Pull request merged**
