### PR TITLE
Adds LUX header and footer

### PR DESCRIPTION
**Pull request by axamei**

### CODE REVIEW

**Comment by tpendragon** [comment]
We'll need to install yarn on dpul-staging1 to deploy this.

**Comment by tpendragon** [comment]
Tried to use yarn for deploy and got an error: `error lux-design-system@0.0.14: The engine "node" is incompatible with this module. Expected version ">= 9.11.1".`.

NPM works, so sticking with that. Maybe something you can look at @axamei if we want to stick with YARN?

**Comment by tpendragon** [comment]
Dropdown user menu is being hidden:
screen shot 2018-07-26 at 10 18 54 am

**Comment by tpendragon** [comment]
Show views are broken:

screen shot 2018-07-26 at 10 20 36 am

**Comment by tpendragon** [comment]
https://github.com/pulibrary/princeton_ansible/pull/300 is necessary to deploy this.

**Comment by escowles** [comment]
I deployed this to staging and tested it compared to the master branch.  I saw some of the same display issues that @tpendragon mentioned above:
* While the page was loading, the header is missing
* On the item show page, the bookmark/email/sms links are unstyled
* If the item show page is loaded using turbolinks, the viewer doesn't display.  If I reload the page or enter the URL in my browser, the viewer works fine.

I did some basic timings and saved the pages with dependencies using Chrome, and found the Lux versions were a little slower and larger.  But turbolinks is a significant factor there, so we should probably talk about the best methodology for testing page sizes and load times.

**Comment by sdellis** [comment]
@escowles this was branched from master before the header/footer rollback. Those issues may be related to problems with that branch. We are going to redo this from master. @axamei is out today. Can we keep this open until she returns?

Re: the benchmarking... Lux is going to add some additional weight while we transition since we are only adding, not yet taking anything away. I agree that we should discuss the best methodology for testing. I think Lighthouse audits are a pretty good way to do this.

**Comment by escowles** [comment]
@sdellis It's totally fine to leave this open a while (as long as you think it's worth having around in fact). Basing off the updated master branch makes sense, and hopefully resolves some of the styling issues.

I'll take a look at Lighthouse.  I don't think modest page size or load time increases would be a problem (in fact, that's what I expect because we're adding Lux and not removing anything else yet). I was mostly just curious about what the impact was.

**Comment by axamei** [comment]
Going to start a new branch from the current master. This is too messy.

**Comment by axamei** [comment]
Feel free to close in favor of #418

**Comment by tpendragon** [comment]
Closed in favor of #418

**Pull request closed without merging**
