### PR TITLE
Using custom error pages

### LINKED ISSUE #231: Need a nicer 5xx page

### PR DESCRIPTION
**Pull request by escowles**
Custom 404 and 500 error pages.

Fixes #231

### CODE REVIEW

**Comment by hackmastera** [comment]
would like to see them; screenshots?

**Comment by tpendragon** [comment]
> I'm not really sure in what case public would still serve while these would not.

Public works if Rails goes down, but that's it.

**Comment by escowles** [comment]
If Rails isn't working, then I'd expect the load balancer to take the node out of service anyway, so I think it's fine to use dynamic error pages.

**Pull request merged**
